/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/chat/[name]': RouteRecordInfo<
      '/chat/[name]',
      '/chat/:name',
      { name: ParamValue<true> },
      { name: ParamValue<false> },
      | never
    >,
    '/crate/open/[userId]/[crateId]': RouteRecordInfo<
      '/crate/open/[userId]/[crateId]',
      '/crate/open/:userId/:crateId',
      { userId: ParamValue<true>, crateId: ParamValue<true> },
      { userId: ParamValue<false>, crateId: ParamValue<false> },
      | never
    >,
    '/HelloWorld': RouteRecordInfo<
      '/HelloWorld',
      '/HelloWorld',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inventoryBadge': RouteRecordInfo<
      '/inventoryBadge',
      '/inventoryBadge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/inventoryChest': RouteRecordInfo<
      '/inventoryChest',
      '/inventoryChest',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/MapPage': RouteRecordInfo<
      '/MapPage',
      '/MapPage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/me': RouteRecordInfo<
      '/me',
      '/me',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/Quests': RouteRecordInfo<
      '/Quests',
      '/Quests',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/shop': RouteRecordInfo<
      '/shop',
      '/shop',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/chat/[name].vue': {
      routes:
        | '/chat/[name]'
      views:
        | never
    }
    'src/views/crate/open/[userId]/[crateId].vue': {
      routes:
        | '/crate/open/[userId]/[crateId]'
      views:
        | never
    }
    'src/views/HelloWorld.vue': {
      routes:
        | '/HelloWorld'
      views:
        | never
    }
    'src/views/inventoryBadge.vue': {
      routes:
        | '/inventoryBadge'
      views:
        | never
    }
    'src/views/inventoryChest.vue': {
      routes:
        | '/inventoryChest'
      views:
        | never
    }
    'src/views/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/views/MapPage.vue': {
      routes:
        | '/MapPage'
      views:
        | never
    }
    'src/views/me.vue': {
      routes:
        | '/me'
      views:
        | never
    }
    'src/views/Quests.vue': {
      routes:
        | '/Quests'
      views:
        | never
    }
    'src/views/shop.vue': {
      routes:
        | '/shop'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
